# Generated by Django 5.1.1 on 2024-09-20 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_alter_partners_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Category_partner',
        ),
    ]
