# Generated by Django 5.1.1 on 2024-09-20 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_rename_category_category_partner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_posts', to='partner.category_partner'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='pic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
